#!/usr/bin/env bash

# ViBe Local Development Runner
# Starts the full local stack: MongoDB (replica set) + Firebase Auth emulator +
# backend + frontend, all concurrently with live reload.
#
# Persistence: BOTH Mongo and the Firebase Auth emulator write to
# ~/.local/share/vibe/ (NOT /tmp) so accounts + courses survive Ctrl+C, sleep,
# emulator crashes, and reboots. See scripts/seed-yaksha.sh for the first-run
# bootstrap of the three default dev accounts (admin / teacher / user @yaksha).
#
# Prerequisites in backend/.env (see .env.example):
#   NODE_ENV=development
#   DB_URL=mongodb://127.0.0.1:27017/?replicaSet=rs0
#   DB_NAME=vibe
#   FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9099
#   GCLOUD_PROJECT=demo-test
#   FIREBASE_PROJECT_ID=demo-test
#   FIREBASE_CLIENT_EMAIL=<throwaway fake>
#   FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIE...\n-----END PRIVATE KEY-----\n"
#   IS_RECAPTCHA_ENABLED=false
#   APP_ORIGINS=http://localhost:5173,http://localhost:5174

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🚀 ViBe Development Server${NC}\n"

# Check pnpm
if ! command -v pnpm &> /dev/null; then
  echo -e "${RED}❌ pnpm not found. Install from https://pnpm.io${NC}"
  exit 1
fi

echo -e "${GREEN}✓ pnpm ${NC}$(pnpm --version)\n"

# Check .env setup
if [ ! -f "backend/.env" ]; then
  echo -e "${YELLOW}⚠️  backend/.env not found${NC}"
  echo -e "${BLUE}Create backend/.env with at minimum:${NC}"
  echo -e "  NODE_ENV=development"
  echo -e "  DB_URL=mongodb://127.0.0.1:27017/?replicaSet=rs0"
  echo -e "  DB_NAME=vibe"
  echo -e "  FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9099"
  echo -e "  GCLOUD_PROJECT=demo-test"
  echo -e "  FIREBASE_PROJECT_ID=demo-test"
  echo -e "  FIREBASE_CLIENT_EMAIL=anything@example.iam.gserviceaccount.com"
  echo -e '  FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIE...\n-----END PRIVATE KEY-----\n"'
  echo -e "  IS_RECAPTCHA_ENABLED=false"
  echo -e "  APP_ORIGINS=http://localhost:5173,http://localhost:5174"
  echo -e "\nSkipping backend start.\n"
  SKIP_BACKEND=1
else
  echo -e "${GREEN}✓ backend/.env found${NC}\n"
fi

if [ ! -f "frontend/.env" ]; then
  echo -e "${YELLOW}⚠️  frontend/.env not found — creating a minimal one${NC}"
  cat > frontend/.env <<EOF
# Auto-generated by run.sh — safe to edit.
VITE_FIREBASE_API_KEY=demo-api-key
VITE_FIREBASE_AUTH_DOMAIN=localhost
VITE_FIREBASE_PROJECT_ID=demo-test
VITE_FIREBASE_STORAGE_BUCKET=demo-test.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=921655600310
VITE_FIREBASE_APP_ID=1:921655600310:web:eafe0aa6299bc49304b217
VITE_FIREBASE_MEASUREMENT_ID=
VITE_BASE_URL=http://localhost:3141/api
VITE_RECAPTCHA_SITE_KEY=
VITE_FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9099
EOF
fi

# Install deps if needed
if [ ! -d "node_modules" ]; then
  echo -e "${BLUE}📦 Installing dependencies...${NC}"
  pnpm install
  echo ""
fi

# Trap to kill all bg processes on exit. Override at the very bottom with one
# that ALSO exports Auth state before tearing down the emulator so the next
# ./run.sh still has the 3 default accounts.
trap 'kill $(jobs -p) 2>/dev/null' EXIT

# Persistent local state locations. Override these env vars if you want to
# point the stack at a different host or test a clean wipe.
export VIBE_DATA_DIR="${VIBE_DATA_DIR:-$HOME/.local/share/vibe}"
VIBE_MONGO_DBPATH="$VIBE_DATA_DIR/mongo/dbpath"
VIBE_MONGO_LOG="$VIBE_DATA_DIR/mongo/mongod.log"
VIBE_AUTH_EXPORT="$VIBE_DATA_DIR/auth-export"
mkdir -p "$VIBE_DATA_DIR/mongo" "$VIBE_AUTH_EXPORT"

# 1. MongoDB — must run as a single-node replica set because BaseService._withTransaction
#    issues transactional writes that standalone mongod rejects.
if [ -z "$SKIP_BACKEND" ]; then
  if ! pgrep -f 'mongod.*27017' > /dev/null; then
    echo -e "${BLUE}🍃 Starting MongoDB (replica set rs0) on :27017${NC}"
    echo -e "    dbpath: ${VIBE_MONGO_DBPATH}"
    mongod --dbpath "$VIBE_MONGO_DBPATH" \
           --logpath "$VIBE_MONGO_LOG" \
           --port 27017 --bind_ip 127.0.0.1 --replSet rs0 --fork > /dev/null
    sleep 2
    # Initiate the replica set if it hasn't been yet.
    mongosh --quiet --eval "
      try { rs.status(); print('Replica set already initialized.'); }
      catch (e) {
        rs.initiate({_id: 'rs0', members: [{_id: 0, host: '127.0.0.1:27017'}]});
        print('Replica set initiated.');
      }
    " > /dev/null
    sleep 2
    echo -e "${GREEN}✓ MongoDB ready${NC}\n"
  else
    echo -e "${GREEN}✓ MongoDB already running${NC}\n"
  fi

  # 2. Firebase Auth emulator — required for both backend admin SDK and frontend
  #    GoogleAuthProvider to mint/verify tokens locally.
  #
  #    --import + --export-on-exit persist accounts to disk so they survive
  #    emulator restarts. Without these, every Ctrl+C wipes admin@/teacher@/user@.
  if ! curl -sf http://127.0.0.1:9099/ > /dev/null 2>&1; then
    echo -e "${BLUE}🔥 Starting Firebase Auth emulator on :9099${NC}"
    echo -e "    export: ${VIBE_AUTH_EXPORT}"
    # --import only (no --export-on-exit). With both flags pointing at the
    # same dir, firebase-tools races the export before the import reads and
    # the file ends up empty. The shutdown trap at the bottom of this file
    # runs `firebase emulators:export` before kill, which is reliable.
    (firebase emulators:start --only auth --project demo-test \
        --import "$VIBE_AUTH_EXPORT" \
        --export-on-exit "$VIBE_AUTH_EXPORT" \
        > /tmp/vibe-firebase-emu.log 2>&1 &)
    for i in {1..30}; do
      sleep 1
      if curl -sf http://127.0.0.1:9099/ > /dev/null 2>&1; then
        break
      fi
    done
    echo -e "${GREEN}✓ Firebase Auth emulator ready${NC}\n"
  else
    echo -e "${GREEN}✓ Firebase Auth emulator already running${NC}\n"
  fi

  # 3. Backend
  echo -e "${BLUE}🔧 Starting backend (port 3141)...${NC}"
  (cd backend && pnpm run dev > /tmp/vibe-backend.log 2>&1 &)
  sleep 3
  for i in {1..20}; do
    if curl -sf http://localhost:3141/reference > /dev/null 2>&1; then
      break
    fi
    sleep 1
  done
  echo -e "${GREEN}✓ Backend ready${NC}\n"

  # 4. Seed default dev accounts (admin/teacher/user @yaksha). Idempotent —
  #    exits silently if all three already exist in both Auth + Mongo.
  if [ -x scripts/seed-yaksha.sh ]; then
    echo -e "${BLUE}🌱 Seeding default accounts...${NC}"
    AUTH_EMU=http://127.0.0.1:9099 \
    DB_URL="${DB_URL:-mongodb://127.0.0.1:27017/?replicaSet=rs0}" \
    DB_NAME="${DB_NAME:-vibe}" \
    PROJECT_ID="${GCLOUD_PROJECT:-demo-test}" \
    bash scripts/seed-yaksha.sh || echo -e "${YELLOW}⚠️  Seed step failed (continuing — accounts may already exist)${NC}"
  fi
fi

# 5. Frontend (always last)
echo -e "${BLUE}⚛️  Starting frontend...${NC}"
(cd frontend && pnpm run dev > /tmp/vibe-frontend.log 2>&1 &)
sleep 3

# Show access URLs
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}📍 Access URLs:${NC}"
echo -e "  Frontend: ${BLUE}http://localhost:5173${NC} (auto-bumps to :5174 if busy)"
echo -e "  Backend:  ${BLUE}http://localhost:3141/reference${NC}"
echo -e "  Firebase Emulator UI: ${BLUE}http://127.0.0.1:4000/auth${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

echo -e "${YELLOW}💡 Tip: Ctrl+C to stop all services${NC}\n"

# Replaces the simple EXIT trap from the top of the file with one that ALSO
# exports Firebase Auth accounts to disk before tearing down. Without this,
# `--export-on-exit` only fires on a fully clean shutdown (rare in practice),
# and the 3 default seed accounts get wiped between dev sessions.
vibe_shutdown() {
  # Best-effort auth export. `firebase emulators:export` against the running
  # emulator writes a metadata file even when `--export-on-exit` would skip.
  if curl -sf http://127.0.0.1:9099/ > /dev/null 2>&1; then
    firebase emulators:export "$VIBE_AUTH_EXPORT" \
      --only auth --force --project demo-test > /dev/null 2>&1 || true
  fi
  kill $(jobs -p) 2>/dev/null
  pkill -P $$ tail 2>/dev/null
}
trap 'vibe_shutdown' EXIT INT TERM
tail -F /tmp/vibe-frontend.log /tmp/vibe-backend.log 2>/dev/null